import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import ThemeToggle from '@/components/ThemeToggle'
import {Switch,Spacer,Link} from '@nextui-org/react'
import MyNavBar from '@/components/MyNavbar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Theme App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <main className={styles.main}>
        <div>
        <h1>App Themes - Light & Dark</h1>
        <code> Toggle switch to change theme.</code>
        <ThemeToggle />
        <h3>This is an example of light theme and dark theme implementaion in NextJS using : </h3>
        <ul>
          <li><Link href="https://nextjs.org/">NextJS</Link></li>
          <li><Link href="https://nextjs.org/">NextUI</Link></li>
          <li>Emotion: <Link href="https://www.npmjs.com/package/@emotion/styled">@emotion/styled</Link> & <Link href="https://www.npmjs.com/package/@emotion/react">@emotion/react</Link></li>
          {/* <ul>
            <li><Link href="https://www.npmjs.com/package/@emotion/styled">@emotion/styled</Link></li>
            <li><Link href="https://www.npmjs.com/package/@emotion/react">@emotion/react</Link></li>
          </ul>
      
          </li> */}
          
        </ul>

       
        <Spacer/>
        {/* <Switch/> */}
        </div>
      </main>
      <footer>
       
      </footer>
    </>
  )
}
